name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "📣 Breaking Changes"
    labels:
      - "breaking_change"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
change-title-escapes: '\<*_&'
replacers:
  - search: '/^- [a-zA-Z\_\-]*\: (.*@.*\))$/gm'
    replace: "- $1"
exclude-labels:
  - "skip-changelog"
  - "github structure"
exclude-contributors:
  - "soloam"
version-resolver:
  major:
    labels:
      - "major"
      - "breaking_change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "maintenance"
      - "documentation"
  default: patch
autolabeler:
  - label: "github structure"
    files:
      - ".github/*"
  - label: "documentation"
    files:
      - "*.md"
    title:
      - "/documentation:/i"
  - label: "fix"
    title:
      - "/bugfix:/i"
      - "/bug:/i"
      - "/fix:/i"
  - label: "feature"
    title:
      - "/add:/i"
      - "/feature:/i"
  - label: "breaking_change"
    title:
      - "/breaking:/i"
      - "/breaking-change:/i"
      - "/breaking_change:/i"
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/soloam/ha-fireflyiii-integration/$RESOLVED_VERSION/total.svg)](https://github.com/soloam/ha-fireflyiii-integration/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/soloam/ha-fireflyiii-integration/issues)
